name: Benchmark

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  walltime:
    runs-on: 'ubuntu-latest'
    name: Walltime Benchmark

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.2"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Apt
        run: sudo apt-get -q update && sudo apt-get -y install $(cat .github/linux_apt_dependencies.txt)

      - name: Install Python packages
        run: uv sync --locked --extra exporters --extra gui --extra server --extra test

      - name: run pytest (benchmark)
        uses: CodSpeedHQ/action@v4
        with:
          run: uv run pytest --codspeed --codspeed-max-rounds=2 --skip-gui-tests
          mode: walltime
          token: ${{ secrets.CODSPEED_TOKEN }}
